CREATE DATABASE DB_CONCESIONARIA 
GO

USE DB_CONCESIONARIA 
GO

CREATE TABLE TBL_CLIENTE(
RUC_CLIENTE VARCHAR(10) PRIMARY KEY,
NOMBRE_CLIENTE VARCHAR(30) NOT NULL,
DIRECCION_CLIENTE VARCHAR(30) NOT NULL, 
CIUDAD_CLIENTE VARCHAR(30) NOT NULL, 
NNUMERO_TELEFONO_CLIENTE VARCHAR(30) NOT NULL, 
)

CREATE TABLE TBL_AUTOMOVIL(
MATRICULA_AUTOMOVIL VARCHAR(10) PRIMARY KEY,
MARCA_AUTOMOVIL VARCHAR(30) NOT NULL,
MODELO_AUTOMOVIL VARCHAR(30) NOT NULL, 
PRECIO_AUTOMOVIL VARCHAR(30) NOT NULL, 
COLOR_AUTOMOVIL VARCHAR(30) NOT NULL, 
RUC_CLIENTE VARCHAR(10) NOT NULL, 
FOREIGN KEY(RUC_CLIENTE) REFERENCES TBL_CLIENTE(RUC_CLIENTE)
)

CREATE TABLE TBL_REVISION(
CODIGO_REVISION VARCHAR(10) PRIMARY KEY,
TIPO_REVISION VARCHAR(50) NOT NULL,
FECHA_REVISION DATE NOT NULL,
MATRICULA_AUTOMOVIL  VARCHAR(10) NOT NULL,
FOREIGN KEY(MATRICULA_AUTOMOVIL) REFERENCES TBL_AUTOMOVIL(MATRICULA_AUTOMOVIL)
)



