USE MASTER
GO

CREATE DATABASE DB_PELICULAS
GO

USE DB_PELICULAS

CREATE TABLE TBL_GENERO(
ID_GENERO VARCHAR(20) PRIMARY KEY,
NOMBRE_GENERO VARCHAR(30) NOT NULL
)

CREATE TABLE TBL_FORMATO(
ID_FORMATO VARCHAR(20) PRIMARY KEY,
NOMBRE_FORMATO VARCHAR(30) NOT NULL,
)

CREATE TABLE TBL_ACTOR(
DNI_ACTOR VARCHAR(15) PRIMARY KEY,
AP_MATERNO_ACTOR VARCHAR(20) ,
AP_PATERNO_ACTOR VARCHAR(20) NOT NULL,
NOMBRES_ACTOR VARCHAR(30) NOT NULL,
DIRECCION_ACTOR VARCHAR(30),
TELEFONO_ACTOR VARCHAR(30),
SEXO_ACTOR VARCHAR(15) NOT NULL,
FECHA_NACIMIENTO_ACTOR DATE NOT NULL,
NACIONALIDAD_ACTOR VARCHAR(30) NOT NULL,
NUMERO_OSCAR_ACTOR INT NOT NULL,
CONDICION_ACTOR VARCHAR(30) NOT NULL
)


CREATE TABLE TBL_PELICULA(
ID_PELICULA VARCHAR(15) PRIMARY KEY,
NOMBRE_PELICULA VARCHAR(20) NOT NULL,
AÑO_PELICULA VARCHAR(20) NOT NULL,
SINOPSIS_PELICULA VARCHAR(100) NOT NULL,
TRAILER_PELICULA VARCHAR NOT NULL,
DURACION_PELICULA TIME NOT NULL,
ID_GENERO VARCHAR(20) NOT NULL,
ID_FORMATO VARCHAR(20) NOT NULL,
FOREIGN KEY(ID_GENERO) REFERENCES TBL_GENERO(ID_GENERO),
FOREIGN KEY(ID_FORMATO) REFERENCES TBL_FORMATO(ID_FORMATO)
)

CREATE TABLE TBL_ACTUAN(
ID_PELICULA VARCHAR (15) NOT NULL,
DNI_ACTOR VARCHAR(15) NOT NULL,
FOREIGN KEY(ID_PELICULA) REFERENCES TBL_PELICULA(ID_PELICULA),
FOREIGN KEY(DNI_ACTOR) REFERENCES TBL_ACTOR(DNI_ACTOR)
)


