CREATE DATABASE DB_TRANSPORTISTA
GO

USE DB_TRANSPORTISTA
GO

CREATE TABLE TBL_PROVINCIA(
ID_PROVINCIA VARCHAR(10) PRIMARY KEY,
NOMBRE_PROVINCIA VARCHAR(30) NOT NULL, 
)

CREATE TABLE TBL_CAMIONERO(
DNI_CAMIONERO VARCHAR(10) PRIMARY KEY,
AP_MATERNO_CAMIONERO VARCHAR(30),
AP_PATERNO_CAMIONERO VARCHAR(30) NOT NULL,
NOMBRES_CAMIONERO VARCHAR(30) NOT NULL,
DIRECCION_CAMIONERO VARCHAR(30) NOT NULL,
TELEFONO_CAMIONERO VARCHAR(30) NOT NULL,
)

CREATE TABLE TBL_CAMION(
MATRICULA_CAMION VARCHAR(10) PRIMARY KEY,
MODELO_CAMION VARCHAR(30) NOT NULL,
)

CREATE TABLE TBL_CONDUCE(
DNI_CAMIONIONERO  VARCHAR(10),
MATRICULA_CAMION VARCHAR(10) NOT NULL,
FECHA_CONDUCE DATE NOT NULL,
FOREIGN KEY(DNI_CAMIONIONERO) REFERENCES TBL_CAMIONERO(DNI_CAMIONERO),
FOREIGN KEY(MATRICULA_CAMION) REFERENCES TBL_CAMION(MATRICULA_CAMION)
)

CREATE TABLE TBL_PAQUETE(
ID_PAQUETE VARCHAR(10) PRIMARY KEY,
DESCRIPCION_PAQUETE VARCHAR(30) NOT NULL,
ORIGEN_PAQUETE VARCHAR(30) NOT NULL,
ID_PROVINCIA VARCHAR(10) NOT NULL,
DNI_CAMIONERO VARCHAR(10) NOT NULL,
FOREIGN KEY(DNI_CAMIONERO) REFERENCES TBL_CAMIONERO(DNI_CAMIONERO),
FOREIGN KEY(ID_PROVINCIA) REFERENCES TBL_PROVINCIA(ID_PROVINCIA)
)