USE MASTER
GO

CREATE DATABASE DB_Panaderia
GO

USE DB_Panaderia

CREATE TABLE TBL_CLIENTE(
ID_CLIENTE VARCHAR(5) PRIMARY KEY,
NOMBRE_CLIENTE VARCHAR(15) NOT NULL,
AP_MATERNO_CLIENTE VARCHAR (30) ,
AP_PATERNO_CLIENTE VARCHAR (30) NOT NULL,
DIRECCION_CLIENTE VARCHAR (30) NOT NULL,
EMAIL_CLIENTE VARCHAR (30) NOT NULL)

CREATE TABLE TBL_ESPECIALISTA(
ID_ESPECIALISTA VARCHAR (20) PRIMARY KEY,
NOMBRE_ESPECIALISTA VARCHAR (20) NOT NULL,
AP_MATERNO_ESPECIALISTA VARCHAR(30),
AP_PATERNO_ESPECIALISTA VARCHAR(30) NOT NULL, 
TELEFONO_ESPECIALISTA VARCHAR(15) NOT NULL
)

CREATE TABLE TBL_INGREDIENTE(
ID_INGREDIENTE VARCHAR(20) PRIMARY KEY,
NOMBRE_INGREDIENTE VARCHAR (30) NOT NULL,
PRESENTACION_INGREDIENTE VARCHAR (100) NOT NULL 
)


CREATE TABLE TBL_PROVEEDOR( 
ID_PROVEEDOR VARCHAR(20) PRIMARY KEY,
NOMBRE_PROVEEDOR VARCHAR(30) NOT NULL, 
DIRECCION_PROVEEDOR VARCHAR(30) NOT NULL
)


CREATE TABLE TBL_PEDIDO (
ID_PEDIDO  VARCHAR(20) PRIMARY KEY, 
FECHA_REALIZACION_PEDIDO DATE NOT NULL, 
FECHA_ENTREGA_PEDIDO DATE NOT NULL,
ID_CLIENTE VARCHAR(5) NOT NULL,
FOREIGN KEY(ID_CLIENTE) REFERENCES TBL_CLIENTE(ID_CLIENTE)
)

CREATE TABLE TBL_ARTICULO(
ID_ARTICULO VARCHAR(20) PRIMARY KEY,
NOMBRE_ARTICULO VARCHAR(30) NOT NULL,
PRECIO_ARTICULO INT NOT NULL,
ID_ESPECIALISTA VARCHAR(20) NOT NULL,
FOREIGN KEY(ID_ESPECIALISTA) REFERENCES TBL_ESPECIALISTA(ID_ESPECIALISTA)
)

CREATE TABLE TBL_SUMINISTRA(
ID_INGREDIENTE VARCHAR(20) NOT NULL,
ID_PROVEEDOR VARCHAR(20) NOT NULL,
FOREIGN KEY(ID_INGREDIENTE) REFERENCES TBL_INGREDIENTE(ID_INGREDIENTE),
FOREIGN KEY(ID_PROVEEDOR) REFERENCES TBL_PROVEEDOR(ID_PROVEEDOR)
)

CREATE TABLE TBL_DETALLE(
ID_PEDIDO VARCHAR(20) NOT NULL,
ID_ARTICULO VARCHAR(20) NOT NULL,
FOREIGN KEY(ID_PEDIDO) REFERENCES TBL_PEDIDO(ID_PEDIDO),
FOREIGN KEY(ID_ARTICULO) REFERENCES TBL_ARTICULO(ID_ARTICULO)
)

CREATE TABLE TBL_CONTIENE(
ID_ARTICULO VARCHAR(20) NOT NULL,
ID_INGREDIENTE VARCHAR(20) NOT NULL,
FOREIGN KEY(ID_ARTICULO) REFERENCES TBL_ARTICULO(ID_ARTICULO),
FOREIGN KEY(ID_INGREDIENTE) REFERENCES TBL_INGREDIENTE(ID_INGREDIENTE)
)






















