USE MASTER
GO

CREATE DATABASE DB_BODEGA
GO

USE DB_BODEGA

CREATE TABLE TBL_CLIENTE(
DNI_CLIENTE VARCHAR(10) PRIMARY KEY,
NOMBRE_CLIENTE VARCHAR(30) NOT NULL,
AP_MATERNO_CLIENTE VARCHAR(30),
AP_PATERNO_CLIENTE VARCHAR(30) NOT NULL,
DIRECCION_CLIENTE VARCHAR(30) NOT NULL,
)


CREATE TABLE TBL_PROVEEDOR(
RUC_PROVEEDOR VARCHAR(20) PRIMARY KEY,
NOMBRE_PROVEEDOR VARCHAR(30) NOT NULL,
DIRECCION_PROVEEDOR VARCHAR(30) NOT NULL,
)


CREATE TABLE TBL_PRODUCTO(
CODIGO_PRODUCTO VARCHAR(10) PRIMARY KEY,
NOMBRE_PRODUCTO VARCHAR(30) NOT NULL,
PRECIO_PRODUCTO INT NOT NULL,
RUC_PROVEEDOR VARCHAR(20) NOT NULL,
FOREIGN KEY(RUC_PROVEEDOR) REFERENCES TBL_PROVEEDOR(RUC_PROVEEDOR)
)

CREATE TABLE TBL_COMRPA(
DNI_CLIENTE VARCHAR(10) NOT NULL,
CODIGO_PRODUCTO VARCHAR(10) NOT NULL,
FOREIGN KEY(DNI_CLIENTE) REFERENCES TBL_CLIENTE(DNI_CLIENTE),
FOREIGN KEY(CODIGO_PRODUCTO) REFERENCES TBL_PRODUCTO(CODIGO_PRODUCTO)
)

